package com.zihao.task1.mapper;

import com.zihao.task1.entity.Building;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BuildingMapper {
    @Insert("INSERT INTO building (dbhisaijutakushurui,dbhisaijutakushoyuu,dbhigaijokyo,dbhigaijokyodaikibohankaiorhankai,dbbukkenmenseki,aplbukkenaddresstodofuken,dbbukkenaddressshigun,dbbukkenaddresschoson,aplbukkenaddressbanchi,aplbukkenaddresspostcode3,dbbousaisyudanitenjigyo,dbbukkenshikichinoshoyukankei,dbbukkentatemonojutaku,dbbukkentatemonohijutaku,dbbukkenkozo,dbbukkentatekatakodatekeishiki,dbnyukyoyoteidateyear,dbnyukyoyoteidatemonth,dbjutakuyoto,dbbukkenkojikanryodateyear,dbbukkenkojikanryodatemonth,dbshikindatetochishikinyear,dbshikindatetochishikinmonth,dbshikindatechukanshikinyear,dbshikindatechukanshikinmonth,dbshikindatesaishushikinyear,dbshikindatesaishushikinmonth,dbkariireininkaishaname,dbchukaihanbainamekana,dbchukaihanbaitantoshanamemei,dbchukaihanbaitantoshanamesei,dbhiyoukensetsuhi,dbhiyoutochisyotokuhi,dbhiyoutotal,dbkariiregakukingaku,dbkariiregakukinri,dbkariiregakuhensaikikan,dbkariiregakunenhensai12no1,dbhensaihouhou,dbhisaishinzokudokyoari,dbsueokikikannonensu,dbsonotaname,dbsonotakingaku,dbsonotahensaikikan,dbsonotanenhensai12no1,dbhiyousonotatotal,dbsogokingaku,dbkinyukikanname,dbshitemname,userid) VALUES (#{dbhisaijutakushurui},#{dbhisaijutakushoyuu},#{dbhigaijokyo},#{dbhigaijokyodaikibohankaiorhankai},#{dbbukkenmenseki},#{aplbukkenaddresstodofuken},#{dbbukkenaddressshigun},#{dbbukkenaddresschoson},#{aplbukkenaddressbanchi},#{aplbukkenaddresspostcode3},#{dbbousaisyudanitenjigyo},#{dbbukkenshikichinoshoyukankei},#{dbbukkentatemonojutaku},#{dbbukkentatemonohijutaku},#{dbbukkenkozo},#{dbbukkentatekatakodatekeishiki},#{dbnyukyoyoteidateyear},#{dbnyukyoyoteidatemonth},#{dbjutakuyoto},#{dbbukkenkojikanryodateyear},#{dbbukkenkojikanryodatemonth},#{dbshikindatetochishikinyear},#{dbshikindatetochishikinmonth},#{dbshikindatechukanshikinyear},#{dbshikindatechukanshikinmonth},#{dbshikindatesaishushikinyear},#{dbshikindatesaishushikinmonth},#{dbkariireininkaishaname},#{dbchukaihanbainamekana},#{dbchukaihanbaitantoshanamemei},#{dbchukaihanbaitantoshanamesei},#{dbhiyoukensetsuhi},#{dbhiyoutochisyotokuhi},#{dbhiyoutotal},#{dbkariiregakukingaku},#{dbkariiregakukinri},#{dbkariiregakuhensaikikan},#{dbkariiregakunenhensai12no1},#{dbhensaihouhou},#{dbhisaishinzokudokyoari},#{dbsueokikikannonensu},#{dbsonotaname},#{dbsonotakingaku},#{dbsonotahensaikikan},#{dbsonotanenhensai12no1},#{dbhiyousonotatotal},#{dbsogokingaku},#{dbkinyukikanname},#{dbshitemname},#{userid})")
    void insertBuilding(Building building);
}
